out_dir: results
metric_best: mae
metric_agg: argmin
accelerator : cuda:1
wandb:
  use: True
  project: pcqm4m
dataset:
  format: OGB
  name: PCQM4Mv2-full
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
cy2:
  type_calayer : res
  scatter_option : mean
  local_mode : double
  local_gnn_type : CustomGatedGCN
  dim_hidden : 256
  n_heads : 8
  dropout : 0.05
  pe_local_mode : double
  pe_act : relu
  act : relu
  pe_norm : batch
  cy2c_self : False
  cy2c_same_attr : True #True 
  cy2c_trans : True #False 
  deg_scaler : False #False 
posenc_CY2C:
  enable : True 
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: TiGTModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 10
  n_heads: 8
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.05
  attn_dropout: 0.2
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 0.0
#  base_lr: 0.0005
#  max_epoch: 300
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 10
#  min_lr: 1e-5
